### ISSUE TITLE
I used your eval.py to visualize but got wrong result

### ISSUE THREAD

**Issue by sunnyHelen** [BingCS/AtLoc#1]
I plot tranjectory use eval.py but get wrong result like this:
![image](https://user-images.githubusercontent.com/28101548/71352956-c14f2600-25cb-11ea-9339-8e8f5981a8bc.png)
the right trajectory should be like this:
![image](https://user-images.githubusercontent.com/28101548/71352994-dd52c780-25cb-11ea-84e3-6138c89f12d6.png)
Even the ground-truth is very wrong. Do you know what may cause this?
Thank you ~

**Comment by BingCS** [comment]
Hi @sunnyHelen, thanks for your interets in our work. From your first figure, I guess there are bugs in your script to load the ground-truth of your dataset (KITTI?). Probably, you didn't transform all locations to global coordiantes.

**Comment by sunnyHelen** [comment]
Well, the description of  pose ground truth of KITTI is like this:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/28101548/71435711-540fd200-273e-11ea-9d59-8adc07cb4ccd.png">
Should the pose of different sequences be transformed to the same global coordinates? I'm very confused. 
Thank you for your help~
