### ISSUE TITLE
Question about training on 7Scenes

### ISSUE THREAD

**Issue by jinyummiao** [BingCS/AtLoc#12]
Hi, thanks for your remarkable work! I have a little question about training the network on the 7-Scenes dataset. Did you train a generic model on just one scene of the 7-Scene and test it on all scene, or train corresponding models on each scene individually? It confused me a lot. Sincerely looking forward to your reply :)

**Comment by BingCS** [comment]
Hi,

Thanks for your interest. I follow a scene-specific training strategy in PoseNet and MapNet, which means the network is trained on each scene individually.

**Comment by jinyummiao** [comment]
Thanks for your kindly help!
