### ISSUE TITLE
How to get the '{:s}_vo_stats.pkl'.format(vo_lib) file?

### ISSUE THREAD

**Issue by sunnyHelen** [BingCS/AtLoc#2]
I think this 'vo_stats.pkl' file is for storing visual odometer pose transformation from existing method, right? But I don't know how to generate it. Could you please help me figure out?
Thank you for your help~

**Comment by BingCS** [comment]
Unfortunately, I cannot support you since this problem is out of the scope of my paper. Please consult MapNet (https://github.com/NVlabs/geomapnet).
