### ISSUE TITLE
about the performance of 7-senses data

### ISSUE THREAD

**Issue by ghoshaw** [BingCS/AtLoc#5]
HI, thanks for your sharing, but I have some questions about the result of the pose regression method.
For A paper "VLocNet++: Deep Multitask Learning for Semantic Visual Localization and Odometry" published in 2018.4.24, their performance is pretty good, as least in the paper and they seems not have much fancy things.
![image](https://user-images.githubusercontent.com/23494873/75326861-59aca400-58b6-11ea-8ae9-bfaa2978afa1.png)
And by now,  no offence, used attention etc, the result on 7-senses seems 10 times less. 
![image](https://user-images.githubusercontent.com/23494873/75327078-bdcf6800-58b6-11ea-90c2-e7d7d906c686.png)
I just get confused, Is that the metrics you used different or something else?

**Comment by BingCS** [comment]
Hi @ghoshaw, thanks for your interests in our work. The metrics used in our paper are the same as the ones in VLocNet++. VLocNet++ makes a good combination of relocalization, odometry and semantic segmentation based on ResNet-50. Similarly, [1] also jointly regresses the global pose as well as the relative pose using ResNet-34, which just achieves 10 times worse results than VLocNet. From these, multi-task learning and deeper architecture indeed boost the performance. You are encouraged to make improvements on localization-related tasks form these two aspects.

[1] Xue, Fei, et al. "Local supports global: Deep camera relocalization with sequence enhancement." ICCV 2019.

**Comment by ghoshaw** [comment]
ok, thanks for your reply!
